#include "emulator/opcode_table.h"
#include "emulator/emulator.h"
#include "emulator/opcode.h"

#define TABLE_ITEM(opcode, instruction_size)                       \
  static const OpcodeTableEntry opcode##_ENTRY = {Opcode_##opcode, \
                                                  instruction_size};
#include "emulator/opcode_defs.h"
#undef TABLE_ITEM
static const OpcodeTableEntry INVALID_ENTRY = {Opcode_INVALID, 1};

static const OpcodeTableEntry *kOpcodeTable[256] = {
    [0x00] = &NOP_ENTRY,     [0x01] = &LXI_ENTRY,     [0x02] = &STAX_ENTRY,
    [0x03] = &INX_ENTRY,     [0x04] = &INR_ENTRY,     [0x05] = &DCR_ENTRY,
    [0x06] = &MVI_ENTRY,     [0x07] = &RLC_ENTRY,     [0x08] = &INVALID_ENTRY,
    [0x09] = &DAD_ENTRY,     [0x0A] = &LDAX_ENTRY,    [0x0B] = &DCX_ENTRY,
    [0x0C] = &INR_ENTRY,     [0x0D] = &DCR_ENTRY,     [0x0E] = &MVI_ENTRY,
    [0x0F] = &RRC_ENTRY,     [0x10] = &INVALID_ENTRY, [0x11] = &LXI_ENTRY,
    [0x12] = &STAX_ENTRY,    [0x13] = &INX_ENTRY,     [0x14] = &INR_ENTRY,
    [0x15] = &DCR_ENTRY,     [0x16] = &MVI_ENTRY,     [0x17] = &RAL_ENTRY,
    [0x18] = &INVALID_ENTRY, [0x19] = &DAD_ENTRY,     [0x1A] = &LDAX_ENTRY,
    [0x1B] = &DCX_ENTRY,     [0x1C] = &INR_ENTRY,     [0x1D] = &DCR_ENTRY,
    [0x1E] = &MVI_ENTRY,     [0x1F] = &RAR_ENTRY,     [0x20] = &INVALID_ENTRY,
    [0x21] = &LXI_ENTRY,     [0x22] = &SHLD_ENTRY,    [0x23] = &INX_ENTRY,
    [0x24] = &INR_ENTRY,     [0x25] = &DCR_ENTRY,     [0x26] = &MVI_ENTRY,
    [0x27] = &DAA_ENTRY,     [0x28] = &INVALID_ENTRY, [0x29] = &DAD_ENTRY,
    [0x2A] = &LHLD_ENTRY,    [0x2B] = &DCX_ENTRY,     [0x2C] = &INR_ENTRY,
    [0x2D] = &DCR_ENTRY,     [0x2E] = &MVI_ENTRY,     [0x2F] = &CMA_ENTRY,
    [0x30] = &INVALID_ENTRY, [0x31] = &LXI_ENTRY,     [0x32] = &STA_ENTRY,
    [0x33] = &INX_ENTRY,     [0x34] = &INR_ENTRY,     [0x35] = &DCR_ENTRY,
    [0x36] = &MVI_ENTRY,     [0x37] = &STC_ENTRY,     [0x38] = &INVALID_ENTRY,
    [0x39] = &DAD_ENTRY,     [0x3A] = &LDA_ENTRY,     [0x3B] = &DCX_ENTRY,
    [0x3C] = &INR_ENTRY,     [0x3D] = &DCR_ENTRY,     [0x3E] = &MVI_ENTRY,
    [0x3F] = &CMC_ENTRY,     [0x40] = &MOV_ENTRY,     [0x41] = &MOV_ENTRY,
    [0x42] = &MOV_ENTRY,     [0x43] = &MOV_ENTRY,     [0x44] = &MOV_ENTRY,
    [0x45] = &MOV_ENTRY,     [0x46] = &MOV_ENTRY,     [0x47] = &MOV_ENTRY,
    [0x48] = &MOV_ENTRY,     [0x49] = &MOV_ENTRY,     [0x4A] = &MOV_ENTRY,
    [0x4B] = &MOV_ENTRY,     [0x4C] = &MOV_ENTRY,     [0x4D] = &MOV_ENTRY,
    [0x4E] = &MOV_ENTRY,     [0x4F] = &MOV_ENTRY,     [0x50] = &MOV_ENTRY,
    [0x51] = &MOV_ENTRY,     [0x52] = &MOV_ENTRY,     [0x53] = &MOV_ENTRY,
    [0x54] = &MOV_ENTRY,     [0x55] = &MOV_ENTRY,     [0x56] = &MOV_ENTRY,
    [0x57] = &MOV_ENTRY,     [0x58] = &MOV_ENTRY,     [0x59] = &MOV_ENTRY,
    [0x5A] = &MOV_ENTRY,     [0x5B] = &MOV_ENTRY,     [0x5C] = &MOV_ENTRY,
    [0x5D] = &MOV_ENTRY,     [0x5E] = &MOV_ENTRY,     [0x5F] = &MOV_ENTRY,
    [0x60] = &MOV_ENTRY,     [0x61] = &MOV_ENTRY,     [0x62] = &MOV_ENTRY,
    [0x63] = &MOV_ENTRY,     [0x64] = &MOV_ENTRY,     [0x65] = &MOV_ENTRY,
    [0x66] = &MOV_ENTRY,     [0x67] = &MOV_ENTRY,     [0x68] = &MOV_ENTRY,
    [0x69] = &MOV_ENTRY,     [0x6A] = &MOV_ENTRY,     [0x6B] = &MOV_ENTRY,
    [0x6C] = &MOV_ENTRY,     [0x6D] = &MOV_ENTRY,     [0x6E] = &MOV_ENTRY,
    [0x6F] = &MOV_ENTRY,     [0x70] = &MOV_ENTRY,     [0x71] = &MOV_ENTRY,
    [0x72] = &MOV_ENTRY,     [0x73] = &MOV_ENTRY,     [0x74] = &MOV_ENTRY,
    [0x75] = &MOV_ENTRY,     [0x76] = &HLT_ENTRY,     [0x77] = &MOV_ENTRY,
    [0x78] = &MOV_ENTRY,     [0x79] = &MOV_ENTRY,     [0x7A] = &MOV_ENTRY,
    [0x7B] = &MOV_ENTRY,     [0x7C] = &MOV_ENTRY,     [0x7D] = &MOV_ENTRY,
    [0x7E] = &MOV_ENTRY,     [0x7F] = &MOV_ENTRY,     [0x80] = &ADD_ENTRY,
    [0x81] = &ADD_ENTRY,     [0x82] = &ADD_ENTRY,     [0x83] = &ADD_ENTRY,
    [0x84] = &ADD_ENTRY,     [0x85] = &ADD_ENTRY,     [0x86] = &ADD_ENTRY,
    [0x87] = &ADD_ENTRY,     [0x88] = &ADC_ENTRY,     [0x89] = &ADC_ENTRY,
    [0x8A] = &ADC_ENTRY,     [0x8B] = &ADC_ENTRY,     [0x8C] = &ADC_ENTRY,
    [0x8D] = &ADC_ENTRY,     [0x8E] = &ADC_ENTRY,     [0x8F] = &ADC_ENTRY,
    [0x90] = &SUB_ENTRY,     [0x91] = &SUB_ENTRY,     [0x92] = &SUB_ENTRY,
    [0x93] = &SUB_ENTRY,     [0x94] = &SUB_ENTRY,     [0x95] = &SUB_ENTRY,
    [0x96] = &SUB_ENTRY,     [0x97] = &SUB_ENTRY,     [0x98] = &SBB_ENTRY,
    [0x99] = &SBB_ENTRY,     [0x9A] = &SBB_ENTRY,     [0x9B] = &SBB_ENTRY,
    [0x9C] = &SBB_ENTRY,     [0x9D] = &SBB_ENTRY,     [0x9E] = &SBB_ENTRY,
    [0x9F] = &SBB_ENTRY,     [0xA0] = &ANA_ENTRY,     [0xA1] = &ANA_ENTRY,
    [0xA2] = &ANA_ENTRY,     [0xA3] = &ANA_ENTRY,     [0xA4] = &ANA_ENTRY,
    [0xA5] = &ANA_ENTRY,     [0xA6] = &ANA_ENTRY,     [0xA7] = &ANA_ENTRY,
    [0xA8] = &XRA_ENTRY,     [0xA9] = &XRA_ENTRY,     [0xAA] = &XRA_ENTRY,
    [0xAB] = &XRA_ENTRY,     [0xAC] = &XRA_ENTRY,     [0xAD] = &XRA_ENTRY,
    [0xAE] = &XRA_ENTRY,     [0xAF] = &XRA_ENTRY,     [0xB0] = &ORA_ENTRY,
    [0xB1] = &ORA_ENTRY,     [0xB2] = &ORA_ENTRY,     [0xB3] = &ORA_ENTRY,
    [0xB4] = &ORA_ENTRY,     [0xB5] = &ORA_ENTRY,     [0xB6] = &ORA_ENTRY,
    [0xB7] = &ORA_ENTRY,     [0xB8] = &CMP_ENTRY,     [0xB9] = &CMP_ENTRY,
    [0xBA] = &CMP_ENTRY,     [0xBB] = &CMP_ENTRY,     [0xBC] = &CMP_ENTRY,
    [0xBD] = &CMP_ENTRY,     [0xBE] = &CMP_ENTRY,     [0xBF] = &CMP_ENTRY,
    [0xC0] = &RNZ_ENTRY,     [0xC1] = &POP_ENTRY,     [0xC2] = &JNZ_ENTRY,
    [0xC3] = &JMP_ENTRY,     [0xC4] = &CNZ_ENTRY,     [0xC5] = &PUSH_ENTRY,
    [0xC6] = &ADI_ENTRY,     [0xC7] = &RST_ENTRY,     [0xC8] = &RZ_ENTRY,
    [0xC9] = &RET_ENTRY,     [0xCA] = &JZ_ENTRY,      [0xCB] = &JMP_ENTRY,
    [0xCC] = &CZ_ENTRY,      [0xCD] = &CALL_ENTRY,    [0xCE] = &ACI_ENTRY,
    [0xCF] = &RST_ENTRY,     [0xD0] = &RNC_ENTRY,     [0xD1] = &POP_ENTRY,
    [0xD2] = &JNC_ENTRY,     [0xD3] = &OUT_ENTRY,     [0xD4] = &CNC_ENTRY,
    [0xD5] = &PUSH_ENTRY,    [0xD6] = &SUI_ENTRY,     [0xD7] = &RST_ENTRY,
    [0xD8] = &RC_ENTRY,      [0xD9] = &RET_ENTRY,     [0xDA] = &JC_ENTRY,
    [0xDB] = &IN_ENTRY,      [0xDC] = &CC_ENTRY,      [0xDD] = &CALL_ENTRY,
    [0xDE] = &SBI_ENTRY,     [0xDF] = &RST_ENTRY,     [0xE0] = &RPO_ENTRY,
    [0xE1] = &POP_ENTRY,     [0xE2] = &JPO_ENTRY,     [0xE3] = &XTHL_ENTRY,
    [0xE4] = &CPO_ENTRY,     [0xE5] = &PUSH_ENTRY,    [0xE6] = &ANI_ENTRY,
    [0xE7] = &RST_ENTRY,     [0xE8] = &RPE_ENTRY,     [0xE9] = &PCHL_ENTRY,
    [0xEA] = &JPE_ENTRY,     [0xEB] = &XCHG_ENTRY,    [0xEC] = &CPE_ENTRY,
    [0xED] = &CALL_ENTRY,    [0xEE] = &XRI_ENTRY,     [0xEF] = &RST_ENTRY,
    [0xF0] = &RP_ENTRY,      [0xF1] = &POP_ENTRY,     [0xF2] = &JP_ENTRY,
    [0xF3] = &DI_ENTRY,      [0xF4] = &CP_ENTRY,      [0xF5] = &PUSH_ENTRY,
    [0xF6] = &ORI_ENTRY,     [0xF7] = &RST_ENTRY,     [0xF8] = &RM_ENTRY,
    [0xF9] = &SPHL_ENTRY,    [0xFA] = &JM_ENTRY,      [0xFB] = &EI_ENTRY,
    [0xFC] = &CM_ENTRY,      [0xFD] = &CALL_ENTRY,    [0xFE] = &CPI_ENTRY,
    [0xFF] = &RST_ENTRY};
